excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://MsQuintillion.github.io
name: External to Internal
description: A spot where I place information that expands my mind and jot down creative ideas.
author: Cat Shark
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 